services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_BASE_URL: http://155.212.161.155:3001/api
        WS_BASE_URL: ws://155.212.161.155:3001
    container_name: saland_frontend
    restart: unless-stopped
    ports:
      - "8082:80"
